### ISSUE TITLE
Activation function for atom_nn

### ISSUE THREAD

**Issue by miaecle** [proteneer/khan#25]
Thanks for putting out this fantastic work @proteneer !  As I am trying to go through the code details, I got a specific question on the activation function used in the NN module.

https://github.com/proteneer/khan/blob/d4e3da77ac23cc5ed2bc6e78571f231a7d093e15/khan/model/nn.py#L48

I suppose this is the activation function for all hidden layers, which takes the form of a gausian. Is it corresponding to the gaussian activation function claimed in the original paper? I cannot identify the source of this activation, so do you have any idea on where can I get a more detailed explanation?

Also, just out of curiosity, how's the final performance on the whole ANI-1 set?

**Comment by proteneer** [comment]
@miaecle All the credit goes to you for the initial tensorflow implementation!

https://github.com/isayev/ASE_ANI/issues/9 (credit to @lilleswing for posting this)
The final performance is comparable what they report in the paper.

But we're using a truncated featurization that isn't what they report in the paper: https://github.com/isayev/ASE_ANI/issues/14

There's a github issue for making the featurization easier to customize, since it's currently hard-coded into the GPU kernels directly. https://github.com/proteneer/khan/issues/15

**Comment by miaecle** [comment]
@proteneer Thanks a lot for the guide! I could fully understand the flexibility issue in featurization, the current version already works pretty nicely for me. And It looks like the activation function is pretty uncommon, though it does make some difference.
